version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5736:5736"
    volumes:
      - ~/.ssh:/opt/motiong/.ssh
      - ~/.ssh/id_rsa:/opt/motiong/.ssh/id_rsa
      - ..:/opt/motiong/code
      - ~/etc/localtime:/opt/motiong/etc/localtime
      - ~/etc/timezone:/opt/motiong/etc/timezone
      - ../.devcontainer/.zshrc:/opt/motiong/.zshrc
    command: ["tail -f /dev/null"]

volumes:
  esdata: